[package]
name = "apollo_client_cli"
version = "0.1.0"
authors = ["TAC Mod Team <info@theseus-aegis.com>"]
edition = "2021"

[lib]
name = "apollo_client"
crate-type = ["cdylib"]

[dependencies]
arma-rs = "1.5"
reqwest = { version = "0.11", features = ["blocking"] }
