name = "Theseus Mods"
prefix = "tac"
mainprefix = "x"
author = "Thesesus Incorporated"

[files]
include = [
    "mod.cpp",
    "LICENSE",
    "*.dll",
    "*.so",
    "README.md",
    "AUTHORS.txt",
    "logo_tac_ca.paa",
    "logo_tac_small_ca.paa"
]

[version]
git_hash = 0

[hemtt.config]
preset = "Hemtt"

[hemtt.release]
folder = "theseus_mods"
