name = "Theseus Mods"
prefix = "tac"
author = "Thesesus Incorporated"

[files]
include = [
    "mod.cpp",
    "LICENSE",
    "*.dll",
    "*.so",
    "README.md",
    "AUTHORS.txt",
    "logo_tac_ca.paa",
    "logo_tac_small_ca.paa"
]

[version]
git_hash = 0

# Unused in HEMTT v1.11 or higher, kept for backwards compatibility
[asc]
enabled = true
exclude = [
    "/initsettings.inc.sqf",
    "/initkeybinds.inc.sqf",
]

[hemtt.config]
preset = "Hemtt"

[hemtt.release]
folder = "theseus_mods"
