name: CI

on:
  push:
    branches:
    - master
  pull_requests:

jobs:
  build:

    runs-on: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout the source code
      uses: actions/checkout@master

    - name: Build
      uses: arma-actions/hemtt@master
      run: hemtt build --release
