name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the source code
      uses: actions/checkout@master

    - name: Build using HEMTT
      uses: arma-actions/hemtt@master
      with:
        command: build --release

    #- uses: actions/upload-artifact@master
    #  with:
    #    name: tac_mods_VERSION.zip
    #    path: releases/tac_mods_*.zip
